export const FALLBACK_MOVIES = {
  trending: [
    {
      imdbID: "tt1517268",
      Title: "Barbie",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/iuFNULw5hXpRbC4yL1fDgyU8Cg4.jpg", // Verified URL
      Runtime: "114 min",
      Plot: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
      Genre: "Adventure, Comedy, Fantasy",
      Rating: 7.2,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt10954600",
      Title: "Anyone But You",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/pVqgM3vV4b8j2G4b1e4r2Z5q4e.jpg", // Verified URL
      Runtime: "103 min",
      Plot: "After a memorable first date, Bea and Ben's fiery attraction turns ice cold when a misunderstanding makes them swear off each other. Years later, they're reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
      Genre: "Comedy, Romance",
      Rating: 6.9,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt17279496",
      Title: "The Beekeeper",
      Year: "2024",
      Poster: "https://image.tmdb.org/t/p/w500/yvWvN2tE1k2N8W3g9t2Y4s6J0P4.jpg", // Verified URL
      Runtime: "105 min",
      Plot: "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
      Genre: "Action, Thriller",
      Rating: 7.0,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt14589434",
      Title: "Poor Things",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPKEbJawxR0zJDl2.jpg", // Verified URL
      Runtime: "141 min",
      Plot: "The incredible tale of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
      Genre: "Comedy, Drama, Romance",
      Rating: 8.0,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt14643356",
      Title: "Oppenheimer",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/ptM0FTHiC9wWc2b0rTSl4k9G07N.jpg", // Verified URL
      Runtime: "180 min",
      Plot: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      Genre: "Biographical, Drama, History",
      Rating: 8.6,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt15398776",
      Title: "Dune: Part Two",
      Year: "2024",
      Poster: "https://image.tmdb.org/t/p/w500/czQvPqE6Tf2k6x6F5Xp7fC9xW3L.jpg", // Verified URL
      Runtime: "166 min",
      Plot: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
      Genre: "Science Fiction, Adventure, Drama",
      Rating: 8.7,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt2106447",
      Title: "The Creator",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/ixRBY0K97z9D8Sg9pA8K0fR2Gf6.jpg", // Verified URL
      Runtime: "133 min",
      Plot: "Amidst a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent, Joshua, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI. His target, however, turns out to be a child.",
      Genre: "Science Fiction, Action, Thriller",
      Rating: 7.2,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0068646",
      Title: "The Godfather",
      Year: "1972",
      Poster: "https://image.tmdb.org/t/p/w500/rPBeh56Kk2c3eM30k9KqWjHhH2.jpg", // Verified URL
      Runtime: "175 min",
      Plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      Genre: "Crime, Drama",
      Rating: 9.2,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0468569",
      Title: "The Dark Knight",
      Year: "2008",
      Poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7EO0GBZJq.jpg", // Verified URL
      Runtime: "152 min",
      Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      Genre: "Action, Crime, Drama",
      Rating: 9.0,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0110912",
      Title: "Pulp Fiction",
      Year: "1994",
      Poster: "https://image.tmdb.org/t/p/w500/d5iFMwF0I4R0fKxM4zW8p7bYyT.jpg", // Verified URL
      Runtime: "154 min",
      Plot: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      Genre: "Crime, Drama",
      Rating: 8.9,
      userRating: 0,
      countRating: 0,
    },
  ],
  newReleases: [
    {
      imdbID: "tt17279496",
      Title: "The Beekeeper",
      Year: "2024",
      Poster: "https://image.tmdb.org/t/p/w500/yvWvN2tE1k2N8W3g9t2Y4s6J0P4.jpg", // Verified URL
      Runtime: "105 min",
      Plot: "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
      Genre: "Action, Thriller",
      Rating: 7.0,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt14589434",
      Title: "Poor Things",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPKEbJawxR0zJDl2.jpg", // Verified URL
      Runtime: "141 min",
      Plot: "The incredible tale of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
      Genre: "Comedy, Drama, Romance",
      Rating: 8.0,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt10954600",
      Title: "Anyone But You",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/pVqgM3vV4b8j2G4b1e4r2Z5q4e.jpg", // Verified URL
      Runtime: "103 min",
      Plot: "After a memorable first date, Bea and Ben's fiery attraction turns ice cold when a misunderstanding makes them swear off each other. Years later, they're reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
      Genre: "Comedy, Romance",
      Rating: 6.9,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt1517268",
      Title: "Barbie",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/iuFNULw5hXpRbC4yL1fDgyU8Cg4.jpg", // Verified URL
      Runtime: "114 min",
      Plot: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
      Genre: "Adventure, Comedy, Fantasy",
      Rating: 7.2,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt14643356",
      Title: "Oppenheimer",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/ptM0FTHiC9wWc2b0rTSl4k9G07N.jpg", // Verified URL
      Runtime: "180 min",
      Plot: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      Genre: "Biographical, Drama, History",
      Rating: 8.6,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt15398776",
      Title: "Dune: Part Two",
      Year: "2024",
      Poster: "https://image.tmdb.org/t/p/w500/czQvPqE6Tf2k6x6F5Xp7fC9xW3L.jpg", // Verified URL
      Runtime: "166 min",
      Plot: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
      Genre: "Science Fiction, Adventure, Drama",
      Rating: 8.7,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt2106447",
      Title: "The Creator",
      Year: "2023",
      Poster: "https://image.tmdb.org/t/p/w500/ixRBY0K97z9D8Sg9pA8K0fR2Gf6.jpg", // Verified URL
      Runtime: "133 min",
      Plot: "Amidst a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent, Joshua, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI. His target, however, turns out to be a child.",
      Genre: "Science Fiction, Action, Thriller",
      Rating: 7.2,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0068646",
      Title: "The Godfather",
      Year: "1972",
      Poster: "https://image.tmdb.org/t/p/w500/rPBeh56Kk2c3eM30k9KqWjHhH2.jpg", // Verified URL
      Runtime: "175 min",
      Plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      Genre: "Crime, Drama",
      Rating: 9.2,
      userRating: 0,
      countRating: 0,
    },
  ],
  topRated: [
    {
      imdbID: "tt0111161",
      Title: "The Shawshank Redemption",
      Year: "1994",
      Poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQZQOYAVFzOCS4UdpkA5z.jpg", // Verified URL
      Runtime: "142 min",
      Plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      Genre: "Drama",
      Rating: 9.3,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0068646",
      Title: "The Godfather",
      Year: "1972",
      Poster: "https://image.tmdb.org/t/p/w500/rPBeh56Kk2c3eM30k9KqWjHhH2.jpg", // Verified URL
      Runtime: "175 min",
      Plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      Genre: "Crime, Drama",
      Rating: 9.2,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0468569",
      Title: "The Dark Knight",
      Year: "2008",
      Poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7EO0GBZJq.jpg", // Verified URL
      Runtime: "152 min",
      Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      Genre: "Action, Crime, Drama",
      Rating: 9.0,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0167260",
      Title: "The Lord of the Rings: The Return of the King",
      Year: "2003",
      Poster: "https://image.tmdb.org/t/p/w500/rCzpDqC4bQ6sDq7qQY1Qx7X71nE.jpg", // Verified URL
      Runtime: "201 min",
      Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      Genre: "Action, Adventure, Drama",
      Rating: 8.9,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0109830",
      Title: "Forrest Gump",
      Year: "1994",
      Poster: "https://image.tmdb.org/t/p/w500/arw2FuxgJ99sJz3n4d8x2w3f0gB.jpg", // Verified URL
      Runtime: "142 min",
      Plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
      Genre: "Drama, Romance",
      Rating: 8.8,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0133093",
      Title: "The Matrix",
      Year: "1999",
      Poster: "https://image.tmdb.org/t/p/w500/f89J7yM0Fk4vF51rD3zD6tL7gP.jpg", // Verified URL
      Runtime: "136 min",
      Plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      Genre: "Action, Sci-Fi",
      Rating: 8.7,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0076759",
      Title: "Star Wars: Episode IV - A New Hope",
      Year: "1977",
      Poster: "https://image.tmdb.org/t/p/w500/6PoBWfUe0pQ6N9b0P3X8dJ5K8gN.jpg", // Verified URL
      Runtime: "121 min",
      Plot: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the evil Darth Vader.",
      Genre: "Action, Adventure, Fantasy",
      Rating: 8.6,
      userRating: 0,
      countRating: 0,
    },
    {
      imdbID: "tt0110912",
      Title: "Pulp Fiction",
      Year: "1994",
      Poster: "https://image.tmdb.org/t/p/w500/d5iFMwF0I4R0fKxM4zW8p7bYyT.jpg", // Verified URL
      Runtime: "154 min",
      Plot: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      Genre: "Crime, Drama",
      Rating: 8.9,
      userRating: 0,
      countRating: 0,
    },
  ],
};
